---
nvm_env: "{{ user_name }}"

nvm_version: v0.31.3

# This sets the nvm global nodejs version.
nvm_default_node_version: stable

# List of nodejs versions to install.
nvm_node_versions:
  - stable

# List of default packages to install on each nodejs version.
nvm_global_packages: []

# List of users to install nvm and nodejs versions to.
# Ignored if nvm_env is set to 'system'
nvm_users: []
