build:
  test:
    image: danlynn/ember-cli
    commands:
      - bower install --allow-root
      - npm install
      - ember test

  bundle:
    image: danlynn/ember-cli
    commands:
      - npm install -g firebase-tools
      - ember build --environment product
      - firebase deploy --token $$FIREBASE_TOKEN

cache:
  mount:
    - node_modules
    - bower_components
    - .git
