---
language: node_js
node_js:
  - "8"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test

deploy:
  - provider: script
    script: npm install -g netlify-cli typescript && npm run build && netlify deploy --prod --dir=dist
    on:
      all_branches: true
      condition: -n $TRAVIS_TAG
  - provider: script
    script: npm install -g netlify-cli typescript && npm run build && netlify deploy -s $NETLIFY_STAGING_SITE_ID --prod --dir=dist
    on: master
