---
- hosts: all
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: application
  roles:
    - base
    - vim
    - nodesource.node

- hosts: ember
  roles:
     - ember
