---
vm_name: last-strawberry
path: /last-strawberry
git_branch: master
vm_os: ubuntu/trusty64
environments:
  - development
server_name: localhost

app_name: '{{ vm_name }}'
user_name: '{{ "vagrant" if target == "virtualbox" else app_name }}'
group_name: '{{ user_name }}'

user_home_path: '/home/{{ user_name }}'

shared_path: '{{ path }}/shared'

app_path: '{{ path }}{{ "/current" if target != "virtualbox" else "" }}'
