---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - build-essential
    - git

- name: Create application group
  group: name={{ group_name }}

- name: Create application user
  user: name={{ user_name }} group={{ group_name }} shell=/bin/bash home={{ user_home_path }}

- name: Create profile.d directory
  file: path={{ profile_d_path }} state=directory owner={{ user_name }} group={{ group_name }}

- name: Create ~/.bash_profile which loads all from ~/profile.d
  template: src=bash_profile.j2 dest={{ user_home_path }}/.bash_profile owner={{ user_name }} group={{ group_name }}

- name: Create ~/.bash_aliases
  template: src=bash_aliases.j2 dest={{ user_home_path }}/.bash_aliases owner={{ user_name }} group={{ group_name }}
